[build]
  command = "npm run build"
  publish = "public"
  environment = {NODE_VERSION = "18.20.4"}

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), geolocation=(), microphone=(), payment=(), usb=()"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    reportOnly = false
    strictDynamic = true
    unsafeEval = false
    unsafeInline = false
    self = false
    https = false
    http = false
